port: 443
services:
  - name: kibotin
    hostname: "localhost"
    routes:
    - prefix: /api
      name: api
      upstream: docker.for.mac.localhost
      port: 8000
    - prefix: /outputs
      name: outputs
      upstream: api
      port: 8000
    - prefix: /
      name: frontend
      upstream: app
      port: 3000

